create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  telegram_update_id bigint not null unique,
  author_id bigint,
  author_username text,
  author_name text,
  status text not null default 'pending'
    check (status in ('pending', 'publishing', 'approved', 'rejected')),
  channel_message_id bigint,
  created_at timestamptz not null default now(),
  decided_at timestamptz
);

alter table public.submissions add column if not exists author_id bigint;
alter table public.submissions add column if not exists author_username text;
alter table public.submissions add column if not exists author_name text;

create table if not exists public.admins (
  telegram_id bigint primary key,
  added_by bigint not null,
  created_at timestamptz not null default now()
);

create table if not exists public.submission_deliveries (
  submission_id bigint not null references public.submissions(id) on delete cascade,
  admin_id bigint not null,
  preview_message_id bigint,
  control_message_id bigint,
  created_at timestamptz not null default now(),
  primary key (submission_id, admin_id)
);

alter table public.submissions enable row level security;
alter table public.admins enable row level security;
alter table public.submission_deliveries enable row level security;

revoke all on table public.submissions, public.admins, public.submission_deliveries
  from anon, authenticated;
revoke all on sequence public.submissions_id_seq from anon, authenticated;

grant select, insert, update on table public.submissions to service_role;
grant select, insert, update, delete on table public.admins to service_role;
grant select, insert, update on table public.submission_deliveries to service_role;
grant usage, select on sequence public.submissions_id_seq to service_role;

comment on table public.submissions is
  'Moderation state and author identity. No post text or media is stored. Identity is cleared after a decision.';
comment on table public.admins is
  'Sub-admin Telegram IDs. The owner remains configured in Vercel ADMIN_ID.';
comment on table public.submission_deliveries is
  'Telegram moderation message IDs for each admin.';

